#!/usr/bin/env python3
"""Generate Bjorklund-Euclidean pattern table for DMGARP V26.

Output: src/euclid-table.inc  (510 bytes, 15 rows x 17 cols x 2 bytes)
  Row index:    N - 2  for N in 2..16
  Column index: K      for K in 0..16
  Cell:         16-bit big-endian pattern (MSB = slot 0)
  Byte offset:  (N - 2) * 34 + K * 2

K = 0:        all zeroes (0x0000)
K = N:        first N MSBs set, low (16-N) bits zero
0 < K < N:    canonical Bjorklund-Euclid, rotated so slot 0 is a hit
K > N:        zero-padded (never read at runtime; edit-time clamps)
"""

from pathlib import Path
from typing import List


def bjorklund_kle(k, n):
    """Recursive Bjorklund for the k <= n-k branch only."""
    assert 0 < k <= n - k
    divisor = n - k
    remainders = [k]
    counts = []
    level = 0
    while True:
        counts.append(divisor // remainders[level])
        remainders.append(divisor % remainders[level])
        divisor = remainders[level]
        level += 1
        if remainders[level] <= 1:
            break
    counts.append(divisor)

    pattern = []

    def build(lvl):
        if lvl == -1:
            pattern.append(0)
        elif lvl == -2:
            pattern.append(1)
        else:
            for _ in range(counts[lvl]):
                build(lvl - 1)
            if remainders[lvl] != 0:
                build(lvl - 2)

    build(level)
    return pattern


def euclid(k, n):
    """Canonical Euclidean rhythm, rotated so pattern[0] == 1 (when k > 0)."""
    if not (0 <= k <= n):
        raise ValueError(f"K={k} out of [0,{n}]")
    if k == 0:
        return [0] * n
    if k == n:
        return [1] * n
    if k <= n - k:
        pat = bjorklund_kle(k, n)
    else:
        pat = [1 - x for x in bjorklund_kle(n - k, n)]
    first = pat.index(1)
    return pat[first:] + pat[:first]


def pattern_to_u16(pat, n):
    """Pack n-bit pattern into 16-bit big-endian (MSB = slot 0, low (16-n) bits zero)."""
    word = 0
    for i, bit in enumerate(pat):
        if bit:
            word |= 1 << (15 - i)
    assert word & ((1 << (16 - n)) - 1) == 0
    return word


def verify():
    """Self-checks before writing the .inc."""
    cases = [
        ((3, 8), 0b10010010_00000000),
        ((5, 8), 0b10110110_00000000),
        ((7, 12), 0b101011010110_0000),
    ]
    for (k, n), expected in cases:
        got = pattern_to_u16(euclid(k, n), n)
        assert got == expected, f"E({k},{n}): got 0x{got:04X}, want 0x{expected:04X}"
    for n in range(2, 17):
        assert pattern_to_u16(euclid(0, n), n) == 0x0000, f"E(0,{n}) != 0"
        full = ((1 << n) - 1) << (16 - n)
        assert pattern_to_u16(euclid(n, n), n) == full, f"E({n},{n}) != all-ones"
    print("OK: E(3,8), E(5,8), E(7,12), E(0,N), E(N,N) all match.")


def render_inc():
    lines = [
        "; Auto-generated by tools/gen-euclid-table.py — do not edit by hand.",
        "; 15 rows (N=2..16) x 17 cols (K=0..16) x 2 bytes = 510 bytes.",
        "; Pattern = 16-bit big-endian, MSB = slot 0; low (16-N) bits = 0.",
        "; Byte offset = (N - 2) * 34 + K * 2.",
        "",
    ]
    for n in range(2, 17):
        words = []
        for k in range(17):
            if k <= n:
                words.append(pattern_to_u16(euclid(k, n), n))
            else:
                words.append(0)
        bytes_out = []
        for w in words:
            bytes_out.append(f"${(w >> 8) & 0xFF:02X}")
            bytes_out.append(f"${w & 0xFF:02X}")
        lines.append(f"; N={n:2d}  (K=0..16)")
        for chunk_start in range(0, 34, 16):
            chunk = bytes_out[chunk_start:chunk_start + 16]
            lines.append("    db " + ",".join(chunk))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main():
    verify()
    out_path = Path(__file__).resolve().parent.parent / "src" / "euclid-table.inc"
    text = render_inc()
    out_path.write_text(text)
    raw_bytes = sum(ln.count("$") for ln in text.splitlines() if ln.lstrip().startswith("db "))
    print(f"Wrote {out_path} ({raw_bytes} bytes of pattern data, 510 expected)")


if __name__ == "__main__":
    main()
